[build]
  base = "www/"

  publish = "dist/"

  command = "curl -fsSL https://deno.land/install.sh | sh && export PATH=\"/opt/buildhome/.deno/bin:$PATH\" && deno task build && cp -r ../src ../*.ts ./dist"

[[edge_functions]]
  path = "/"
  function = "homepage"

[[headers]]
  for = "/*.ts"
  [headers.values]
    Content-Type = "application/typescript; charset=utf-8"
